name: deploy

on:
  push:
    branches: ['main']
    paths:
      - '**'

jobs:
  build:
    name: Build and Deploy
    timeout-minutes: 60
    runs-on: ubuntu-latest

    permissions:
      contents: write
      id-token: write
      
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Setup Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x

      - name: Create .env file
        run: |
          echo "SOLANA_ENDPOINT=${{ secrets.SOLANA_ENDPOINT }}" > .env
          echo "SOLANA_PRICE_ENDPOINT=${{ secrets.SOLANA_PRICE_ENDPOINT }}" >> .env

      - name: Build step
        run: "deno task build"

      - name: Upload to Deno Deploy
        uses: denoland/deployctl@v1
        with:
          project: "skeet-fresh-edge-solana"
          entrypoint: "./main.ts"
          root: "."